name: 'path-watcher'
description: 'path-watcher'

outputs:
  backend:
    value: ${{ steps.modified.outputs.backend }}
  frontend:
    value: ${{ steps.modified.outputs.frontend }}
  cdk:
    value: ${{ steps.modified.outputs.cdk }}

inputs:
  token:
    required: true

runs:
  using: "composite"
  steps:

    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v3.1.0
      with:
        fetch-depth: 0

    - name: Path-watcher
      id: modified
      shell: bash
      run: |
        npm i @actions/core @actions/github @octokit/rest minimatch
        node .github/workflows/path-watcher.js
      env:
        GITHUB_TOKEN: ${{ inputs.token }}